services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - bookmarks-postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_HOST_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U  ${DB_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    image: bookmarks-app:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      #  auto=none -- let spring load schema.sql to init the db
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_SQL_INIT_MODE: always
      SPRING_SQL_INIT_PLATFORM: postgresql
      SERVER_PORT: 8080
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health
      #     LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
    ports:
      - "8080:8080"
      - "5005:5005"
    restart: unless-stopped

# If there is another volume with the same name, bad things happen
volumes:
  bookmarks-postgres-data:
