services:
  db:
    image: postgres:15
    container_name: bookmark-postgres
    environment:
      POSTGRES_DB: bookmarktree
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "app_user" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    image: bookmark-tree
    container_name: bookmark-tree-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bookmarktree
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_PLATFORM=postgresql
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=default
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres-data:
